version: "3.9"

services:
  test:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - mtls-network

  envoy:
    image: envoyproxy/envoy:v1.26.0
    container_name: envoy
    ports:
      - "8443:443"
      - "9901:9901"
    volumes:
      - ./certs:/etc/certs:ro
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    networks:
      - mtls-network

  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./certs:/etc/certs:ro
    networks:
      - mtls-network

networks:
  mtls-network:
    driver: bridge
